name: 'Set status'
description: 'Sets the provided status for a given context on a commit'

inputs:
  sha:
    required: true
    description: 'Commit'
  
  context:
    required: true
    description: 'Context'

  status:
    required: true
    description: 'Status'

  github_token:
    required: true
    description: 'Github token'
  
  description:
    required: false
    description: 'Description'
    default: 'Running'
 
 conclusion:
    required: false
    description: 'Conclusion'
    default: 'neutral'

runs:
  using: "composite"
  steps:
  - run: |
      curl --fail --request POST --url "https://api.github.com/repos/irfanazam1/merequeuedemo/check-runs" \
      --header "Authorization: Bearer ${{ inputs.github_token }}" \
      --header 'Accept:  application/vnd.github+json' \
      --data '{"name": "${{ inputs.context }}", "status": "${{ inputs.status }}", "head_sha": "${{ inputs.sha }}", "conclusion": "${{ inputs.conclusion}}", "output":{"title":"${{ inputs.context }}","summary":" ${{ inputs.description }} ","text":""}}'
    shell: bash
