queue_rules:
  - name: default
    conditions:
      - check-success='MergeQueue CI'

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - check-success='MergeQueue CI'
    actions:
      queue:
        name: default
