queue_rules:
  - name: default
    conditions:
      - check-success='on-commit / on-commit'
      - check-success='on-commit / finaliz status'

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - check-success='on-commit / on-commit'
      - check-success='on-commit / finaliz status'
    actions:
      queue:
        name: default
