queue_rules:
  - name: default
    conditions:
      - check-success='CI Start'

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
    actions:
      queue:
        name: default
