queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=2"
      - check-success='Completed'

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - "#approved-reviews-by>=2"
      - check-success='Completed'
    actions:
      queue:
        name: default
