name: CI
on:
  push:
    branches:
      - main
      - staging
      - trying
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/set-status
      with:
        sha: ${{ github.sha }}
        context: 'MergeQueue CI'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        status: pending
        description: Running
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - run: |
        mvn clean package
  
  ci-success:
    name: ci
    if: ${{ success() }}
    needs:
      - build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
    
  
