name: on-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  on-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/set-status
      with:
        sha: ${{ github.sha }}
        context: 'MergeQueue CI'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        status: pending
        description: running
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - run: |
        mvn clean package
        
  finalize-status:
    needs: on-commit
    name: finalize status
    runs-on: ubuntu-latest
    if: always()
    steps:
    - uses: actions/checkout@v3 
    - uses: ./.github/actions/set-status
      with:
        sha: ${{ github.sha }}
        context: 'MergeQueue CI'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        status: success
        description: Completed
    
  
