name: on-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  on-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 11
    - run: |
        mvn clean package
